export const languageList = [
  { code: "en", nativeName: "English", englishName: "English", flag: "🇬🇧" },
  { code: "ur", nativeName: "اردو", englishName: "Urdu", flag: "🇵🇰" },
  { code: "ar", nativeName: "العربية", englishName: "Arabic", flag: "🇸🇦" },
  { code: "fr", nativeName: "Français", englishName: "French", flag: "🇫🇷" },
  { code: "de", nativeName: "Deutsch", englishName: "German", flag: "🇩🇪" },
  { code: "it", nativeName: "Italiano", englishName: "Italian", flag: "🇮🇹" },
  { code: "es", nativeName: "Español", englishName: "Spanish", flag: "🇪🇸" },
  { code: "tr", nativeName: "Türkçe", englishName: "Turkish", flag: "🇹🇷" },
  { code: "ru", nativeName: "Русский", englishName: "Russian", flag: "🇷🇺" },
  { code: "zh-CN", nativeName: "简体中文", englishName: "Chinese", flag: "🇨🇳" },
  { code: "ja", nativeName: "日本語", englishName: "Japanese", flag: "🇯🇵" },
  { code: "ko", nativeName: "한국어", englishName: "Korean", flag: "🇰🇷" },
  { code: "hi", nativeName: "हिन्दी", englishName: "Hindi", flag: "🇮🇳" },
  { code: "bn", nativeName: "বাংলা", englishName: "Bengali", flag: "🇧🇩" },
  { code: "nl", nativeName: "Nederlands", englishName: "Dutch", flag: "🇳🇱" },
  { code: "pt", nativeName: "Português", englishName: "Portuguese", flag: "🇵🇹" },
  { code: "pl", nativeName: "Polski", englishName: "Polish", flag: "🇵🇱" },
  { code: "el", nativeName: "Ελληνικά", englishName: "Greek", flag: "🇬🇷" },
  { code: "th", nativeName: "ไทย", englishName: "Thai", flag: "🇹🇭" },
  { code: "vi", nativeName: "Tiếng Việt", englishName: "Vietnamese", flag: "🇻🇳" },
  { code: "id", nativeName: "Bahasa Indonesia", englishName: "Indonesian", flag: "🇮🇩" },
  { code: "ms", nativeName: "Bahasa Melayu", englishName: "Malay", flag: "🇲🇾" },
];
